### ISSUE TITLE
Black screen crash (Server Closed) near Piglin Alchemist Forge 1.19.2

### ISSUE THREAD

**Issue by TacoLite** [seymourimadeit/Piglin-Proliferation#10]
For ease of access, logs listed first:
[debug.log](https://github.com/seymourimadeit/Piglin-Proliferation/files/13405123/debug.log)
[latest.log](https://github.com/seymourimadeit/Piglin-Proliferation/files/13405124/latest.log)

Context: Fought some Piglin Alchemists in the Nether (Crimson Forest Biome) and one Piglin Alchemist died of undetermined causes not far from my location. I approached the location in question, and was met with a black screen that hung until there was a forced "Server Closed" message. Due to the black screen, I don't have much more information to provide, my apologies.

I peaked at the logs and did notice the term ai.brains and "Piglin Alchemist" thrown around.

Let me know if you need additional information, I may be able to provide.

**Comment by seymourimadeit** [comment]
Sorry, but we do not support 1.19.2 anymore
