### ISSUE TITLE
[1.20.1] Crossmod interaction crash with the @Industrial Foregoing Mob Crusher ("Bound must be positive".)

### ISSUE THREAD

**Issue by Gbergz** [seymourimadeit/Piglin-Proliferation#15]
**Info**:
Seems to be a crossmod interaction crash with the Mob Crusher from Industrial Foregoing. Some type of item being dropped or something. Not entirely sure.

**Crash message** Bound must be positive.
**Crash-log**: https://gist.githubusercontent.com/Gbergz/64f933c3056aa25737a5ce328ca360e9/raw/3f7383b61978aafe9c1630bde29d81608094ec03/gistfile1.txt

**Versions**:
Minecraft: 1.20.1
Forge: 47.2.17
Piglin Proliferation: 1.1.2
Industrial Foregoing: 3.5.15

**Other info**:
From a user in discord who could reproduce this issue had this to say as it might be caused by the item Buckler:
Screenshot:
![sc](https://github.com/seymourimadeit/Piglin-Proliferation/assets/26634554/2660d807-25f4-4250-94dd-cce99466cb30)
![sc2](https://github.com/seymourimadeit/Piglin-Proliferation/assets/26634554/a205234d-e504-4d44-8866-8c1bf00384bb)

**Comment by seymourimadeit** [comment]
For now I simply suggest disabling the ability to have brutes equip bucklers in the config files until the next update releases.
