### ISSUE TITLE
Crashes when trying to load mod with other mods in 1.18.2; possible mod incompatibility

### ISSUE THREAD

**Issue by DarthCaesium** [seymourimadeit/Piglin-Proliferation#2]
Unsure if it's on your end or it's on another mod's end, but I can't use this mod at all as it crashes when trying to load it. I have a crash log that may be of some use for you: 

https://paste.ee/p/7Xrv0

Also, I'm using Linux Mint 20.3, and the latest version of Forge for 1.18.2 (version 40.1.73, also happened with version 40.1.69). From what I can gather from the crash log, it might be clashing with Oh The Biomes You'll Go due to something to do with Piglin anger states and zombification, but I'm unsure why it would be doing this.

**Comment by seymourimadeit** [comment]
The log you sent had Piglin Proliferation disabled, please send a log of it with it actually enabled.

**Comment by seymourimadeit** [comment]
Also please try to recreate this bug in 1.19.

**Comment by seymourimadeit** [comment]
nvm fixed
