### ISSUE TITLE
1.20.1 forge, latest version: tallestred.piglinproliferation.PPEvents.entityJoin

### ISSUE THREAD

**Issue by Mollusky** [seymourimadeit/Piglin-Proliferation#22]
My server is saying that this mod seems to be the issue, I have the error log (or, at least some of it) provided here: https://mclo.gs/i5YBkLc 

Before the crash I also got this error: Worker-Main-505/ERROR No key selector in MapLike[{event_delay:0,event_distance:0.0f,range:8,source:{pos:[I;-425,-56,-205],type:"minecraft:block"}}]

I can provide more information if needed, this just seemed to be the important part for now.

No one in my server has entered the Nether yet as far as I'm aware. Error occurs when loading particular chunks I think? This has happened once or twice before with the same issue being cited. It could also just be an error with ModernFix / some sort of incompatibility since that's one of the mods listed as well in the error. 

(This is my first time ever making a error report, so I hope this was the correct way to go about it. I'm also new to server-running and code reading, so I definitely don't 100% know what I'm talking about here, hah. Anyways, thank you for your hard work! Love what you've done with the mod with my testing in private worlds)

**Comment by seymourimadeit** [comment]
Please send this information to the ModernFix issue tracker, as it seems like they have a mixin that might be interfering. 

I'll try to investigate this on my side.

**Comment by seymourimadeit** [comment]
I hope this issue is fixed in the next release, if not, please comment on this so I can reopen and investigate further.
