### ISSUE TITLE
reduce passive performance consumption (placebo lib compatibility?)

### ISSUE THREAD

**Issue by Heatwu** [seymourimadeit/Piglin-Proliferation#27]
![image](https://github.com/user-attachments/assets/cb7dfe86-97b2-48db-af75-6faf2d2464b4)

I don't even have the buckler in my inventory/out

**Comment by seymourimadeit** [comment]
On first glance this seems to be a weird product of Apotheosis’ own features, but I’d need the full spark log link to fully investigate this

**Comment by Heatwu** [comment]
https://spark.lucko.me/AQr8WpLOln

**Comment by seymourimadeit** [comment]
Is there a chance you can test this .jar file out to see if lag is reduced by recent changes I've implemented in development? Thanks.
[piglinproliferation.zip](https://github.com/user-attachments/files/16422455/piglinproliferation.zip)

**Comment by Heatwu** [comment]
https://spark.lucko.me/bEwh9v5fN8
this patch has fixed the issue, I also tested the brute bashing the player and the player using the buckler; no crashes
