### ISSUE TITLE
new piglin heads dont wiggle their ears

### ISSUE THREAD

**Issue by guhguhguhguhguh** [seymourimadeit/Piglin-Proliferation#8]
in 1.20 regular piglin heads will wiggle their ears when a redstone signal is applied but the 3 new heads (brute, the new guy, and zombie)  dont wiggle their ears

**Comment by seymourimadeit** [comment]
Can't recreate on 1.20. Do you have any other mods that may conflict (eg, optifine) 

https://github.com/seymourimadeit/Piglin-Proliferation/assets/55965249/438c42f9-007a-4175-a44f-4e612e35d7dd

**Comment by guhguhguhguhguh** [comment]
No

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by seymourimadeit** [comment]
Since I'm unable to recreate this in game with the latest version of forge too I'd like to see a video of how you setup your redstone with the piglin heads and a modlist too (if there are any mods, even ones that wouldn't conflict)

**Comment by seymourimadeit** [comment]
Turns out it was the piglin wall heads having the problem.

**Comment by guhguhguhguhguh** [comment]
Yes now that you say that it I tried It and it is only the ones on the floor that work

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
